debug

diff --git a/.github/workflows/trivy.yaml b/.github/workflows/trivy.yaml
--- a/.github/workflows/trivy.yaml
+++ b/.github/workflows/trivy.yaml
@@ -143,3 +143,12 @@ jobs:
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.TRIVY_SLACK_WEBHOOK_URL }}
           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+      
+      - name: Fail Pipeline if Vulnerability Found
+        run: |
+          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ] || [ "$MEDIUM" -gt 0 ] || [ "$LOW" -gt 0 ]; then
+            echo "Vulnerabilities detected — failing the job"
+            exit 1
+          else
+            echo "No vulnerabilities found."
+          fi
